MODEL:
  NAME: 'E2EModelBAN'
INPUT:
  END_TO_END: True
  SEQUENCE_LENGTH: 100
SOLVER:
  BATCH_SIZE: 4
  LR: 1e-2
  OPTIMIZER: 'SGD'
  MAX_EPOCHS: 20
  MILESTONES: [6, 8, 12, 16]
#  MILESTONES: [8, 12, 16, 20]
TEST:
  THRESHOLD: 0.3
OUTPUT_DIR: 'output/sc_transformer'