MODEL:
  NAME: 'E2EModel'
INPUT:
  END_TO_END: True
  SEQUENCE_LENGTH: 100
SOLVER:
  BATCH_SIZE: 4
  LR: 1e-2
  OPTIMIZER: 'SGD'
  MAX_EPOCHS: 30
  MILESTONES: [12, 16]
TEST:
  THRESHOLD: 0.3
OUTPUT_DIR: 'output/ttt'